services:
  - type: web
    name: om-pay-api
    runtime: docker
    buildCommand: "docker build -t om-pay ."
    startCommand: "./start.sh"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mongo
      - key: MONGO_DB_URL
        value: "mongodb+srv://lydevtech:Mouhamm%40dsws632@cluster0.xeygdpt.mongodb.net/"
      - key: MONGO_DB_DATABASE
        value: "om_pay_db"
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
