services:
  - type: web
    name: om-pay-api
    env: docker
    buildCommand: "docker build -t om-pay ."
    startCommand: "docker run -p $PORT:80 om-pay"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromSecret: db_host
      - key: DB_PORT
        fromSecret: db_port
      - key: DB_DATABASE
        fromSecret: db_name
      - key: DB_USERNAME
        fromSecret: db_username
      - key: DB_PASSWORD
        fromSecret: db_password
      - key: CACHE_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info

secrets:
  - key: db_host
    value: "dpg-d48f51ngi27c73cjrhmg-a.oregon-postgres.render.com"
  - key: db_port
    value: "5432"
  - key: db_name
    value: "om_pay"
  - key: db_username
    value: "om_pay_user"
  - key: db_password
    value: "r5SKL0PoFIoX0kPwmrdwQnIVAbOc1sXo"
