services:
  - type: web
    name: om-pay-api
    env: docker
    buildCommand: "docker build -t om-pay ."
    startCommand: "docker run -p $PORT:80 om-pay"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: om-pay-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: om-pay-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: om-pay-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: om-pay-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: om-pay-db
          property: password
      - key: CACHE_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info

databases:
  - name: om-pay-db
    databaseName: om_pay
    user: om_pay_user
    plan: free
