services:
  - type: web
    name: om-pay-api
    env: docker
    buildCommand: "docker build -t om-pay ."
    startCommand: "docker run -p $PORT:80 om-pay"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromSecret: db_host
      - key: DB_PORT
        fromSecret: db_port
      - key: DB_DATABASE
        fromSecret: db_name
      - key: DB_USERNAME
        fromSecret: db_username
      - key: DB_PASSWORD
        fromSecret: db_password
      - key: CACHE_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info

secrets:
  - key: db_host
    value: "your_db_host"
  - key: db_port
    value: "5432"
  - key: db_name
    value: "your_db_name"
  - key: db_username
    value: "your_db_username"
  - key: db_password
    value: "your_db_password"
