services:
  - type: web
    name: om-pay-api
    runtime: docker
    buildCommand: "docker build -t om-pay ."
    startCommand: "./start.sh"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: "dpg-d48f51ngi27c73cjrhmg-a.oregon-postgres.render.com"
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: "om_pay"
      - key: DB_USERNAME
        value: "om_pay_user"
      - key: DB_PASSWORD
        value: "r5SKL0PoFIoX0kPwmrdwQnIVAbOc1sXo"
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
