services:
  - type: web
    name: om-pay-api
    env: docker
    buildCommand: "docker build -t om-pay ."
    startCommand: "docker run -p $PORT:80 om-pay"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: "your_db_host"
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: "your_db_name"
      - key: DB_USERNAME
        value: "your_db_username"
      - key: DB_PASSWORD
        value: "your_db_password"
      - key: CACHE_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
